// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libghostty binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the tarballs.
// For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'libghostty-v0.0.4';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames.
const assetHashes = <String, String>{
  'libghostty-aarch64-ios-simulator.dylib': 'c378e86526f732bc2fa9b662693f1ecaae5bf13fa65b251bb969960e0daa72a3',
  'libghostty-aarch64-ios.dylib': '07481cdc66697991fcb0596222b57e8ced8c5ab7744ed3d6567fece4d02d7bee',
  'libghostty-aarch64-linux-android.so': '1d6f08c6a4f5d5c61c0ad0083082a3e700667ccaa0812c1382e0f440f839a2bc',
  'libghostty-aarch64-linux.so': '1e1cbb0ac62ef9759a592b8bb74d051f7bfb7b5c6a880cbec0843df2c5ec5427',
  'libghostty-aarch64-macos.dylib': 'd91662320a6725e22fb7f9723352ecf86dbb623b15f56ac38a42f5bde0a0702b',
  'libghostty-arm-linux-androideabi.so': '1459d34d1dc90cc7ddeef8a89c5759cfb52b038bbd7e4f4008c2a061796064e3',
  'libghostty-wasm32-freestanding.wasm': 'a0cea03e80bfece05b6a697a0768c1d4e4866d3d2a73ff3989e1462af6df7a07',
  'libghostty-x86_64-ios-simulator.dylib': '6ba84f55460c7191c542d955c77d31039d6c4c0d63841b0394a046cf31f1cd15',
  'libghostty-x86_64-linux-android.so': 'f173cc824fd68a75cc52af12a50ce3d09433b6055ccb006ad0beb4d9d6d9fccb',
  'libghostty-x86_64-linux-musl.so': '0c42d8b0ae5e78d0b35e2b5b16b2ec93e7ba2168b07708cebecf92e55d2579da',
  'libghostty-x86_64-linux.so': 'ec8ca60703466e3963fde6045fde20658febd69f7b9e8dc69a9b60a3f5a474f7',
  'libghostty-x86_64-macos.dylib': '6a1796fe2eefdf3796324b6509cd1cde96f6d94d289667bdc7ca315c83502b0e',
  'libghostty-x86_64-windows.dll': 'b6ca6e45e2391612fe742c18ef57b75f96f39788ad954ae01f11935ae9d7c39f',
};
