// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libghostty binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the tarballs.
// For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'libghostty-v0.0.9';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames.
const assetHashes = <String, String>{
  'libghostty-aarch64-ios-simulator.dylib': 'c25e41afce42b6f2de1966013cfab7d22792f46cadf5006e3ad24b15062f7ccd',
  'libghostty-aarch64-ios.dylib': '85376a533c385a27dd68d9fe55ec4500ace944f082bb16e822a7839219341650',
  'libghostty-aarch64-linux-android.so': 'f726f23a0aacd83c49a5e164e67d803ffb837f8948f99c5a673332e7054e06c9',
  'libghostty-aarch64-linux-gnu.so': '5059029d3196a6d7ece0ade33881a0ead9d022eb4120a30abb8f39f074772264',
  'libghostty-aarch64-macos.dylib': '3e2320dbfb35e97f731d89cd100703ea8aadd0571259e7436afebab1e9554423',
  'libghostty-arm-linux-androideabi.so': 'ad1bfb256d5007097edcf08830708ab1019d1b0afaed9bab1e6878c20d9d4fe6',
  'libghostty-wasm32-freestanding.wasm': 'a0772590b9e09f3d9f9365007af8c0f3b9d214afbd8242f70ba505933f30a463',
  'libghostty-x86_64-ios-simulator.dylib': '54070b8c656e2e9e83b98379173442063e751015848cbc44cec93ec949d8c077',
  'libghostty-x86_64-linux-android.so': '6f9a44d0ccbbbe07311842d4be8fc9ac9ba7f85eb8767860b96362fe34dd1235',
  'libghostty-x86_64-linux-gnu.so': '0ef7ff21b2bb61a37512e820cb8e0086b29b605bc41ed885867963ae82faea52',
  'libghostty-x86_64-linux-musl.so': '97e8994e0441446b0891b6b3df5c29536dfd7c8dd623095e2bec427f3325b4f8',
  'libghostty-x86_64-macos.dylib': '5e43daa986aedf8db8d742a184b70ab463d7324a3675464a8d68ebd3550ef7a0',
  'libghostty-x86_64-windows.dll': 'ed49e58f2541c1e4c7281889f33f71fa794a81a6b9e49b63b9998c2ca00aefe1',
};
