// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libghostty binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the tarballs.
// For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'libghostty-v0.0.8';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames.
const assetHashes = <String, String>{
  'libghostty-aarch64-ios-simulator.dylib': 'e810fa70ef84aaa10d2a8e960292869b2b8270055d9daa80feb91abd1c79bd5e',
  'libghostty-aarch64-ios.dylib': '0b9731f134dce5aaf8bb82818f63e050f59755c4c1a400e560d7658b038ac019',
  'libghostty-aarch64-linux-android.so': 'd29eab3190e933d5bab3ea95e9a1aa27a26e32bb4edcf664f5a0af9db7a6fe18',
  'libghostty-aarch64-linux-gnu.so': '0b40532dd7816689cc265bc20b551f0524780832026ff42850204bbc840016b1',
  'libghostty-aarch64-macos.dylib': 'ae0f3e5be8b3c3babdbf48b32e9705b9ec36a45286a432b09a2e724918ce2337',
  'libghostty-arm-linux-androideabi.so': '424fecf17323f12c050bae6f220725ab3e56388348d3dfc1dbeb4f3db1e3a3ed',
  'libghostty-wasm32-freestanding.wasm': '4291133bedd4913cad681a930dd7ae6d1b0efec4f161c6deecd984ded0d0c278',
  'libghostty-x86_64-ios-simulator.dylib': '8b379f068b7d358bf51b7dbcc068bfa3809f18a1b891fc34de2f75b38101638a',
  'libghostty-x86_64-linux-android.so': 'b7f69de2e3f729ef865e175dc2ea9436a9ae5166796c53562f9fd5d11905755f',
  'libghostty-x86_64-linux-gnu.so': 'f0b1f7a3d9a2411e783775cec54c6aac20c0836d3cbfd9827df6f6da050c9fe8',
  'libghostty-x86_64-linux-musl.so': '9a0b2745a195b91831800ccc07faa5f3a1ab5ccea743937067edddabeaa354c4',
  'libghostty-x86_64-macos.dylib': '2ae1d6890db053776a6bdda312f359ce99055a8004cdeedb84a5bbff234336b3',
  'libghostty-x86_64-windows.dll': 'e4fccbcc0146dba73f5b71363402f038bdf52ed494bfe879634a13ae5f99694f',
};
