/// Extracts enums from ffigen-generated bindings into a separate file.
library;

import 'dart:io';

/// Extracts all enum definitions from [bindingsPath] into [enumsPath] and
/// adds an import of the enums file back into the bindings.
///
/// If [docPrefix] is provided, strips it from doc comment lines so that
/// C type references match their renamed Dart names.
void extractEnums({
  required String bindingsPath,
  required String enumsPath,
  String? docPrefix,
}) {
  final lines = File(bindingsPath).readAsStringSync().split('\n');
  final enumBuf = StringBuffer(
    '// Generated by tool/ffigen.dart. Do not edit.\n'
    '// Platform-independent enum definitions extracted from '
    '${Uri.file(bindingsPath).pathSegments.last}.\n\n',
  );
  final bindingsBuf = StringBuffer();

  var i = 0;
  var addedImport = false;

  while (i < lines.length) {
    final docStart = i;
    while (i < lines.length && lines[i].trimLeft().startsWith('///')) {
      i++;
    }

    if (i < lines.length && lines[i].startsWith('enum ')) {
      var braceDepth = 0;
      while (i < lines.length) {
        braceDepth += '{'.allMatches(lines[i]).length;
        braceDepth -= '}'.allMatches(lines[i]).length;
        i++;
        if (braceDepth == 0) break;
      }

      for (var j = docStart; j < i; j++) {
        enumBuf.writeln(lines[j]);
      }
      enumBuf.writeln();
    } else {
      for (var j = docStart; j < i; j++) {
        bindingsBuf.writeln(lines[j]);
      }
      if (i < lines.length) {
        bindingsBuf.writeln(lines[i]);
        if (!addedImport && lines[i].startsWith('import ')) {
          final enumFileName = Uri.file(enumsPath).pathSegments.last;
          bindingsBuf.writeln("import '$enumFileName';");
          addedImport = true;
        }
        i++;
      }
    }
  }

  var enumStr = enumBuf.toString();
  var bindingsStr = bindingsBuf.toString();

  if (docPrefix != null) {
    final docRegex = RegExp('(/// .*)$docPrefix');
    enumStr = enumStr.replaceAllMapped(
      docRegex,
      (m) => m.group(0)!.replaceFirst(docPrefix, ''),
    );
    bindingsStr = bindingsStr.replaceAllMapped(
      docRegex,
      (m) => m.group(0)!.replaceFirst(docPrefix, ''),
    );
  }

  File(enumsPath).writeAsStringSync(enumStr);
  stdout.writeln('Extracted enums to $enumsPath');

  File(bindingsPath).writeAsStringSync(bindingsStr);
  stdout.writeln('Updated $bindingsPath (enums extracted, import added)');
}
