/// Generates typed WASM export declarations from C headers via ffigen.
///
/// Maps C types to WASM value types following the WebAssembly calling
/// convention:
/// - All integer types (bool, enum, size_t, uint8-32, int8-32) map to
///   [int] (i32/i64).
/// - float and double map to [double] (f32/f64).
/// - Pointers and function pointers map to [Pointer] (i32 table index).
/// - Struct/union returns use the sret convention: output pointer as
///   first parameter, void return.
library;

import 'dart:io';

import 'package:ffigen/ffigen.dart' show FfiGenerator;
import 'package:ffigen/src/code_generator.dart';
import 'package:ffigen/src/context.dart';
import 'package:ffigen/src/header_parser.dart' as ffigen;
import 'package:logging/logging.dart';

import 'naming.dart';

/// Parses C headers using [generator] and writes a JS interop extension type
/// named [typeName] to [outputPath].
void generateWasmExports({
  required FfiGenerator generator,
  required String outputPath,
  required String typeName,
}) {
  final library = ffigen.parse(Context(Logger.root, generator));
  final buf = StringBuffer('''
// Generated by tool/ffigen.dart. Do not edit.
// ignore_for_file: non_constant_identifier_names

import 'dart:js_interop';

typedef Pointer = int;

extension type $typeName(JSObject _) implements JSObject {
  external JSObject get memory;

''');

  for (final binding in library.bindings) {
    if (binding is! Func) continue;

    final type = binding.functionType;
    final sret = _isStructReturn(type.returnType);
    final ret = sret ? 'void' : _wasmType(type.returnType);

    // Emit C doc comments from the header if available.
    final doc = binding.dartDoc;
    if (doc != null && doc.isNotEmpty) {
      for (final line in doc.split('\n')) {
        final trimmed = line.trimLeft();
        if (trimmed.startsWith('///')) {
          buf.writeln('  $trimmed');
        } else {
          buf.writeln('  /// $trimmed');
        }
      }
    }

    buf.write('  external $ret ${binding.originalName}(');

    // WASM struct-by-value returns use the sret convention: the caller
    // passes an output pointer as the first argument and the function
    // returns void.
    var paramIndex = 0;
    if (sret) {
      buf.write('Pointer sret');
      paramIndex = 1;
    }

    for (final (_, p) in type.parameters.indexed) {
      if (paramIndex > 0) buf.write(', ');
      buf.write('${_wasmType(p.type)} ${safeName(p.name)}');
      paramIndex++;
    }
    buf.writeln(');');
  }

  buf.writeln('}');

  File(outputPath).writeAsStringSync(buf.toString());
  stdout.writeln('Generated WASM exports in $outputPath');
}

/// Returns true if [type] is a struct or union, which requires the sret
/// calling convention in WASM (output pointer as first parameter).
bool _isStructReturn(Type type) => type is Compound;

/// Maps a C type to its WASM JS interop representation.
///
/// WASM has four value types: i32, i64, f32, f64. All integer types
/// (including bool, enum, size_t, and function pointers as table indices)
/// map to [int]. Float and double map to [double]. Pointers map to
/// [Pointer] (typedef for [int]).
String _wasmType(Type type) {
  if (type is PointerType) return 'Pointer';
  final native = type.getNativeType().trim().toLowerCase();
  if (native == 'void') return 'void';
  if (native.contains('float') || native.contains('double')) return 'double';
  return 'int';
}
