// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of ptyx binaries downloaded by the build hook.
// For the initial source-first release, no prebuilt binaries are published.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'ptyx-v0.0.1';

/// SHA256 hashes for pre-built native binaries. Keys are artifact filenames.
const assetHashes = <String, String>{};
